server:
  port: 9084
spring:
  application:
    name: mq2


#springboot-admin
  boot:
    admin:
      client:
        url: http://localhost:9085/monitor
        username: root
        password: root
        instance:
          service-base-url: http://localhost:9084
          name: mq2
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
#management.endpoints.web.exposure.include=*



  redis:
    database: 0
    host: localhost
    port: 6379
    password:



  rabbitmq:
    host: 10.12.14.155
    port: 5672
    password: guest
    #虚拟host 可以不设置,使用server默认host
#    virtual-host: JCcccHost

    #消息确认配置项
    # 确认消息已发送到交换机(Exchange)
    publisher-confirms: true
    #确认消息已发送到队列(Queue)
    publisher-returns: true

    #这个配置是针对消息消费端的配置
    listener:
      direct:
        acknowledge-mode: MANUAL #消费方手动ack
      simple:
        concurrency: 10 #
        max-concurrency: 50 # 最大线程数
        prefetch: 10 #RabbitMQ就会使得每个Consumer在同一个时间点最多处理一个Message，
        acknowledge-mode: MANUAL #消费方手动ack
        retry:
          enabled: true  #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          max-attempts: 5  #最大重试次数
          initial-interval: 5000 #重试间隔时间（单位毫秒）
          max-interval: 12000  #重试最大时间间隔（单位毫秒）
          multiplier: 5 #应用于前一重试间隔的乘法器
        default-requeue-rejected: false #默认true 重试次数超过上面的设置之后是否丢弃（false不丢弃时需要写相应代码将该消息加入死信队列）




