server:
  port: 9083
spring:
  application:
    name: mq
  boot:
    admin:
      client:
        instance:
          prefer-ip: true
        url: http://10.12.14.163:9085
        service-base-url: http://10.12.14.163:9083
#spring.boot.admin.client.instance.prefer-ip=true
#spring.boot.admin.client.service-base-url=http://10.12.14.163:9083
#management.endpoint.health.show-details=ALWAYS

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


  rabbitmq:
    host: 10.12.14.155
    port: 5672
    username: guest
    password: guest
    #虚拟host 可以不设置,使用server默认host
#    virtual-host: JCcccHost

    #消息确认配置项
    # 确认消息已发送到交换机(Exchange)
    publisher-confirms: true
    #确认消息已发送到队列(Queue)
    publisher-returns: true

    #这个配置是针对消息消费端的配置
    listener:
      simple:
        retry:
          enabled: true  #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          max-attempts: 5  #最大重试次数
          initial-interval: 1000 #重试间隔时间（单位毫秒）
          max-interval: 10000  #重试最大时间间隔（单位毫秒）
          multiplier: 1 #应用于前一重试间隔的乘法器。


